version: '3'
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      # context is location dockerfile
      context: .
      args:
        - NODE_ENV=production
    environment:
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    # environment:
    #   - NODE_ENV=production
    # env_file:
    #   - .env.prod
    command: npm run start:prod
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
