version: '3'
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      # context is location dockerfile
      context: .
      args:
        - NODE_ENV=production
    # environment:
    #   - NODE_ENV=production
    # env_file:
    #   - .env.prod
    command: npm run start:prod
